### ISSUE TITLE
Conformance tool crashes during the transaction

### ISSUE THREAD

**Issue by armenabgaryan** [fido-alliance/conformance-tools-issues#213]
Tool version 0.9.17

Conformance tool crashes during the transaction on Authentication and ASM Auth test cases.
After tapping the "Authorize" button, the conformance app crashes with the following exception:

FATAL EXCEPTION: main
                                                                                        Process: org.fidoalliance.mobile.conformancetools, PID: 9504
                                                                                        java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=61905, result=-1, data=Intent { (has extras) }} to activity {org.fidoalliance.mobile.conformancetools/org.fidoalliance.mobile.conformancetools.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.success(java.lang.String)' on a null object reference
                                                                                            at android.app.ActivityThread.deliverResults(ActivityThread.java:4268)
                                                                                            at android.app.ActivityThread.handleSendResult(ActivityThread.java:4312)
                                                                                            at android.app.ActivityThread.-wrap19(Unknown Source:0)
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                            at android.os.Looper.loop(Looper.java:164)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                                         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.success(java.lang.String)' on a null object reference
                                                                                            at org.fidoalliance.mobile.uafasm.uafASMCallResult(uafasm.java:124)
                                                                                            at org.fidoalliance.mobile.uafasm.onActivityResult(uafasm.java:174)
                                                                                            at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:159)
                                                                                            at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:359)
                                                                                            at android.app.Activity.dispatchActivityResult(Activity.java:7266)
                                                                                            at android.app.ActivityThread.deliverResults(ActivityThread.java:4264)
                                                                                            at android.app.ActivityThread.handleSendResult(ActivityThread.java:4312) 
                                                                                            at android.app.ActivityThread.-wrap19(Unknown Source:0) 
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644) 
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                            at android.os.Looper.loop(Looper.java:164) 
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                                            at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by jenkay** [comment]
This was not reproducible on v0.9.18

**Comment by herrjemand** [comment]
Okay. Closing it then. *)
