### ISSUE TITLE
Problem in Authr-Generic-1 Generic FIDO protocol tests

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#402]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?

Latest

## What is the OS and the version are you running?

Windows 10

## Issue description

I tried to test Authr-Generic-1 Generic FIDO protocol tests but I have the below error.
•	P-2 If GetInfo contains Options field: Check that every option in options is of type Boolean. Additionally: (a) If "up" is set to true, check that metadata.userVerificationDetails contains VerificationMethodDescriptor that has "userVerification" set to USER_VERIFY_PRESENCE (b) If "uv" is set to true, check that metadata.userVerificationDetails contains VerificationMethodDescriptor that has "userVerification" set to either of USER_VERIFY_PASSCODE/FINGERPRINT/VOICEPRINT/FACEPRINT/EYEPRINT/HANDPRINT/PATTERN (c) If "uv" and "up" is false, check that metadata.userVerificationDetails contains VerificationMethodDescriptor that has "userVerification" set to either of USER_VERIFY_NONE‣
AssertionError: Metadata statement missing VerificationMethodDescriptor for test of user presence!: expected false to be true
    at r.it (eval at compileCode (js/sandbox.js:25:26), <anonymous>:2459:24)
    at c (js/vendor/mocha.min.js:1:39830)
    at s.h.run (js/vendor/mocha.min.js:1:39766)
    at g.runTest (js/vendor/mocha.min.js:1:45107)
    at file:///C:/Users/yscho/AppData/Local/F/app-0.10.110/resources/app/app/js/vendor/mocha.min.js:1:45969
    at o (js/vendor/mocha.min.js:1:44419)
    at file:///C:/Users/yscho/AppData/Local/F/app-0.10.110/resources/app/app/js/vendor/mocha.min.js:1:44488
    at s (js/vendor/mocha.min.js:1:43894)
    at file:///C:/Users/yscho/AppData/Local/F/app-0.10.110/resources/app/app/js/vendor/mocha.min.js:1:44306
    at h (js/vendor/mocha.min.js:1:1072)

I have looked at Authr-Generic-1.js and found that there is a bug in line 99 as follows.

          if(!options['up'] && !options['uv']) {                assert.isTrue(metadataUserVerificationDetailsContainsAnyOf([USER_VERIFICATION_METHODS_TO_INT.USER_VERIFY_NONE]), 'Metadata statement missing VerificationMethodDescriptor for test of user presence!'); }

I think the above code should be fixed as follows            } 
           
            if(options['up'] == false ) 
                if (options['uv'] == false) {
                assert.isTrue(metadataUserVerificationDetailsContainsAnyOf([USER_VERIFICATION_METHODS_TO_INT.USER_VERIFY_NONE]), 'Metadata statement missing VerificationMethodDescriptor for test of user presence!');
            }

Can you please check the above code to fix the problem?

**Comment by herrjemand** [comment]
@sangraecho Additionally ! was missing. Thanks for reporting *)
