### ISSUE TITLE
UAF 1.1 Metadata statement tests, P-15 fails

### ISSUE THREAD

**Issue by k-tono** [fido-alliance/conformance-tools-issues#437]
Protocol: UAF v1.1
Client
Tool version: 1.4.1, 1.4.2
OS: Android 6.0.1

Metadata statement tests P-15 

> Required "attachmentHint", of type unsigned long. MUST be a 32-bit number representing the bit fields defined by the ATTACHMENT_HINT constants in the FIDO Registry of Predefined Values [FIDORegistry].  MUST not be zero.

 fails with error:
```
TypeError: Cannot read property '1' of undefined
    at r.it (eval at compileCode (assets/scripts/sandbox.js:23:26), &lt;anonymous&gt;:5027:35)
    at c (assets/scripts/vendor/mocha.min.js:1:39830)
    at s.h.run (assets/scripts/vendor/mocha.min.js:1:39766)
    at g.runTest (assets/scripts/vendor/mocha.min.js:1:45107)
    at file:///android_asset/www/assets/scripts/vendor/mocha.min.js:1:45969
    at o (assets/scripts/vendor/mocha.min.js:1:44419)
    at file:///android_asset/www/assets/scripts/vendor/mocha.min.js:1:44488
    at s (assets/scripts/vendor/mocha.min.js:1:43894)
    at file:///android_asset/www/assets/scripts/vendor/mocha.min.js:1:44306
    at h (assets/scripts/vendor/mocha.min.js:1:1072)
```
Our metadata contains attachmentHint field with value 1
"attachmentHint": 1,

No any modification done on metadata file, all tests are passing successfully on tool version 1.4.0
Test starts failing from tool version 1.4.1 and also reproducible on 1.4.2

**Comment by herrjemand** [comment]
@k-tono Uploaded 1.4.3 *)
