### ISSUE TITLE
CTAP2 Attestation certificate error 

### ISSUE THREAD

**Issue by antonio-fr** [fido-alliance/conformance-tools-issues#547]
## What protocol and version of the protocol are you testing?
FIDO2 CTAP2

## What is your implementation class?
Authr

## What is the version of the tool are you using?
v1.3.4

## What is the OS and the version are you running?
Windows 10

## Issue description
In the MakeCredential Response test named "P-2" :

Authr-MakeCred-Resp-2 Test "packed" attestation
P-2 If "x5c" presented: (a) Check that ...
```
Error: the string "Signature: unsupported public key alg: ecdsa" was thrown, throw an Error :)
    at h.fail (js/vendor/mocha.min.js:1:43543)
    at app/js/vendor/mocha.min.js:1:46426
    at u (js/vendor/mocha.min.js:1:39333)
    at s.run (js/vendor/mocha.min.js:1:39719)
    at h.runTest (js/vendor/mocha.min.js:1:45264)
    at app/js/vendor/mocha.min.js:1:46126
    at r (js/vendor/mocha.min.js:1:44576)
    at app/js/vendor/mocha.min.js:1:44645
    at r (js/vendor/mocha.min.js:1:44051)
    at app/js/vendor/mocha.min.js:1:44463
```

Our x5c certificate is using ecdsa-with-sha256 (ecdsaWithSHA256, ANSI X9.62 ECDSA algorithm with SHA256 = 1.2.840.10045.4.3.2) signature, same as we did in U2F. This uses the "Basic Attestation" method.

Is there any restriction on the signature algorithm used in the attestation certificate?

For what we can conclude from reading the FIDO2 standard :
"_It is suggested that implementers prefer ECDSA in combination with SHA-256 / SHA-512 hash algorithms. However, the RSA algorithm is also supported. See [FIDORegistry] "Authentication Algorithms" and "Public Key Representation Formats" for a list of generally supported cryptographic algorithms._"

This FIDORegistry document lists for signature : 
* ALG_SIGN_SECP256R1_ECDSA_SHA256_RAW
* ALG_SIGN_SECP256R1_ECDSA_SHA256_DER
* ALG_SIGN_RSASSA_PSS_SHA256_RAW
* ALG_SIGN_RSASSA_PSS_SHA256_DER
* ALG_SIGN_SECP256K1_ECDSA_SHA256_RAW
* ALG_SIGN_SECP256K1_ECDSA_SHA256_DER
* ALG_SIGN_SM2_SM3_RAW
* ALG_SIGN_RSA_EMSA_PKCS1_SHA256_RAW
* ALG_SIGN_RSA_EMSA_PKCS1_SHA256_DER

**Comment by herrjemand** [comment]
@antonio-fr What algorithm are you having issues with?

**Comment by antonio-fr** [comment]
I just report that we are facing "_Signature: unsupported public key alg: ecdsa_" when testing our authenticator implementation. The x509 certificate provided by the auhtr is signed using "ES256" ecdsa-with-sha256 (ecdsaWithSHA256, ANSI X9.62 ECDSA algorithm with SHA256 = 1.2.840.10045.4.3.2 = secp256r1).
I think that maybe the conformance tools is only capable of verifying RSA2048 signatures for the certificate. We need some more details and info about the error we are facing. Then we would be sure that it is our device under test or a limitation of the present testing tool.

**Comment by herrjemand** [comment]
Could you email a sample of response and metadata to conformance-tools@fidoalliance.org

**Comment by Cristianopalazzi** [comment]
Hi @antonio-fr, have you received any feedback? I have the same problem.
Thank you.

**Comment by antonio-fr** [comment]
I sent by email, as requested, lots of relevant info on Feb 27th evening. Waiting for their feedback on this.

**Comment by antonio-fr** [comment]
Well, after digging alone into this issue, it was finally solved by providing the right root certificate in the attestationRootCertificates field in the metadata statement file. We were afraid it was because the signature used was ECDSA, as it is not the case of many devices manufacturers. It was just because the metadata file was not updated for this point.
